spring:
  application:
    name: usian-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.58.130:3306/h1906b?characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.58.130:7001
        - 192.168.58.130:7002
        - 192.168.58.130:7003
        - 192.168.58.130:7004
        - 192.168.58.130:7005
        - 192.168.58.130:7006
  rabbitmq:
    host: 192.168.58.130
    username: admin
    password: 1111
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual

    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

  #配置缓存首页商品分类的 key
portal_catresult_redis_key: portal_catresult_redis_key
ITEM_INFO: ITEM_INFO
BASE: BASE
DESC: DESC
PARAM: PARAM
ITEM_INFO_EXPIRE: 86400
#分布式锁
SETNX_LOCK_KEY: SETNX_LOCK_KEY
DESC_LOCK_KEY: DESC_LOCK_KEY
